services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tracking-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: 'Asia/Ho_Chi_Minh'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
